name: 02-DL-FF
on: 
  workflow_dispatch:
    inputs:
      filename:
        required: true
        description: Filename
      url:
        required: true
        description: url m3u8
jobs:
  streamlink:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing
      run : |
        sudo apt update
        sudo wget 'https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz'
        sudo tar xvf ffmpeg-master-latest-linux64-gpl.tar.xz
        sudo chmod +x ffmpeg-master-latest-linux64-gpl/bin/ffmpeg ffmpeg-master-latest-linux64-gpl/bin/ffprobe
        sudo mv ffmpeg-master-latest-linux64-gpl/bin/ffmpeg ffmpeg-master-latest-linux64-gpl/bin/ffprobe /usr/local/bin/
        sudo rm -rf ffmpeg-master-latest-linux64-gpl ffmpeg-master-latest-linux64-gpl.tar.xz
        sudo chmod +x go-ul
        sudo cp go-ul /usr/local/bin/go-ul
    - name: Download with ffmpeg
      run: |
        ffmpeg -i '${{github.event.inputs.url}}' -c copy '${{github.event.inputs.filename}}.ts'
        ffmpeg -i '${{github.event.inputs.filename}}.ts' -c copy -map_metadata -1 -movflag +faststart '${{github.event.inputs.filename}}.mp4'
    - name: Uploading
      env:
        VOE_FTP: ${{ secrets.VOE_FTP }}
      run: |
        go-ul ftp -f './${{github.event.inputs.filename}}.mp4' -r -u '${{ env.VOE_FTP }}/YT/' -O 
        curl --upload-file "./${{github.event.inputs.filename}}.mp4" "https://transfer.sh/${{github.event.inputs.filename}}.mp4"
    - name: Delete file
      run: rm "./${{github.event.inputs.filename}}.ts"
