name: 04-DL
on: 
  workflow_dispatch:
    inputs:
      filename:
        required: true
        description: Filename
      url:
        required: true
        description: url m3u8
jobs:
  streamlink:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with: 
        python-version: '3.8'
    - name: Install Requirements
      run : |
        sudo apt update
        sudo apt install -y unzip wget ffmpeg mkvtoolnix
        python3 -m pip install --upgrade pip
        pip3 install requests streamlink
    - name: Downloading TS
      timeout-minutes: 360
      run: streamlink -o '${{github.event.inputs.filename}}.ts' '${{github.event.inputs.url}}' best
    - name: Post-processing
      run: |
        ffmpeg -hide_banner -i './${{github.event.inputs.filename}}.ts' -c copy -map_metadata -1 'output/${{github.event.inputs.filename}}.mp4'
        ffmpeg -hide_banner -i './${{github.event.inputs.filename}}.ts' -vn -c:a copy -map_metadata -1 'output/${{github.event.inputs.filename}}.m4a'
    - name: Uploading Video
      run: |
        curl -F "file=@output/${{github.event.inputs.filename}}.m4a" https://api.anonfiles.com/upload
        curl -F "file=@output/${{github.event.inputs.filename}}.mp4" https://api.anonfiles.com/upload
        curl --upload-file "output//${{github.event.inputs.filename}}.m4a" "https://transfer.sh/${{github.event.inputs.filename}}.m4a"
        curl --upload-file "output//${{github.event.inputs.filename}}.mp4" "https://transfer.sh/${{github.event.inputs.filename}}.mp4"
    - name: Delete file
      run: rm "./${{github.event.inputs.filename}}.ts"
