name: ${{github.event.inputs.url}}
on: 
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: Youtube URL
      audioOnly:
        type: boolean
        description: dl Audio-only
        default: false
jobs:
  Y-DL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Requirements
      run : |
        sudo apt update
        sudo add-apt-repository -y ppa:savoury1/ffmpeg5
        sudo add-apt-repository -y ppa:savoury1/ffmpeg4
        sudo apt install -y ffmpeg
        chmod +x ytarchive
        sudo cp ytarchive /usr/local/bin/ytarchive
        chmod +x go-ul
        sudo cp go-ul /usr/local/bin/go-ul
        sudo mkdir Y
    - name: Downloading TS
      timeout-minutes: 360
      if: ${{github.event.inputs.audioOnly == 'false'}}
      run: sudo ytarchive -v -w -t -o "Y/[%(upload_date)s] %(id)s %(title)s" --add-metadata --separate-audio --threads 8 "${{github.event.inputs.url}}" best
    - name: Downloading TS-AudioOnly
      if: ${{github.event.inputs.audioOnly == 'true'}}
      run: sudo ytarchive -v -w -t -o "Y/[%(upload_date)s] %(id)s %(title)s" --add-metadata --threads 8 "${{github.event.inputs.url}}" audio_only
    - name: Uploading
      timeout-minutes: 240
      run: go-ul pixeldrain gofile anonfiles catbox -d 'Y/' -r -o output/link.txt
    - name: Upload Downloaded Videos
      uses: actions/upload-artifact@v3
      with:
        name: link
        path: output
