name: 07-DL-F
on: 
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: FC2 URL
      name:
        required: true
        description: Channel name
      audioOnly:
        type: boolean
        description: DL Audio-only
        default: false
jobs:
  FC2-DL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with: 
        python-version: '3.9'
    - name: Installing
      run : |
        sudo apt update -y
        sudo wget -q 'https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz'
        sudo chmod +x go-ul
        sudo cp go-ul /usr/local/bin/go-ul
        sudo pip install --upgrade fc2-live-dl
        sudo pip install --upgrade 'git+https://github.com/HoloArchivists/fc2-live-dl.git#egg=fc2-live-dl'
        sudo tar xvf ffmpeg-master-latest-linux64-gpl.tar.xz
        sudo chmod +x ffmpeg-master-latest-linux64-gpl/bin/ffmpeg ffmpeg-master-latest-linux64-gpl/bin/ffprobe
        sudo mv ffmpeg-master-latest-linux64-gpl/bin/ffmpeg ffmpeg-master-latest-linux64-gpl/bin/ffprobe /usr/local/bin/
        echo ${{github.event.inputs.name}} ${{github.event.inputs.url}} > output/links.txt
        sudo rm -rf ffmpeg-master-latest-linux64-gpl ffmpeg-master-latest-linux64-gpl.tar.xz
    - name: Downloading ${{github.event.inputs.name}} ${{github.event.inputs.url}}
      timeout-minutes: 360
      env:
        URL: ${{github.event.inputs.url}}
        AUDUI_ONLY: ${{github.event.inputs.audioOnly}}
      run: python fccdl.py
    - name: Uploading
      timeout-minutes: 240
      env:
        VOE_FTP: ${{ secrets.VOE_FTP }}
      run: |
        go-ul pixeldrain anonfiles gofile catbox ftp -d 'output/' -r -u '${{ env.VOE_FTP }}/FC2' -O -o 'output/links.txt'
        mv output/links.txt "output/${{github.event.inputs.name}}.txt"
    - name: Upload link ${{github.event.inputs.name}}s Videos
      uses: actions/upload-artifact@v3
      with:
        name: ${{github.event.inputs.name}}
        path: output/*.txt
